[project]
name = "raspberry-monitor-ha"
version = "0.1.0"
description = ""
authors = [
    {name = "dvk-net",email = "denniskot@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "pydantic (>=2.5.0)",
    "pydantic-settings (>=2.1.0)",
    "python-dotenv (>=1.0.0)",
    "ha-mqtt-discoverable (>=0.24.2,<0.25.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "psutil (>=7.2.2,<8.0.0)"
]

[tool.poetry]
packages = [{include = "raspberry_monitor_ha", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pi_monitor_start = "raspberry_monitor_ha.main"