from raspbery_monitor_ha import state_pollers, base_classes

configured_sensors = [
    base_classes.create_sensor(
        name="Uptime", 
        unit_of_measurement=None, 
        device_class=None,
        icon="mdi:clock",
        get_state_func=state_pollers.get_uptime_seconds
    ),
    base_classes.create_sensor(
        name="CPU_Temperature",
        unit_of_measurement="°C",
        device_class="temperature",
        get_state_func=state_pollers.get_cpu_temperature
    ),
    base_classes.create_sensor(
        name="RP1_Temperature",
        unit_of_measurement="°C",
        device_class="temperature",
        get_state_func=state_pollers.get_rp1_adc_temperature
    ),
    base_classes.create_sensor(
        name="WiFi_Download_Speed",
        unit_of_measurement="Mbit/s",
        device_class="data_rate",
        icon="mdi:download-network",
        get_state_func=state_pollers.get_wifi_download_speed
    ),
    base_classes.create_sensor(
        name="WiFi_Upload_Speed",
        unit_of_measurement="Mbit/s",
        device_class="data_rate",
        icon="mdi:upload-network",
        get_state_func=state_pollers.get_wifi_upload_speed
    ),
    base_classes.create_sensor(
        name="CPU_Load",
        unit_of_measurement="%",
        device_class="power_factor",
        icon="mdi:cpu-64-bit",
        get_state_func=state_pollers.get_cpu_load
    ),
    base_classes.create_sensor(
        name="Memory_Usage",
        unit_of_measurement="%",
        device_class="power_factor",
        icon="mdi:memory",
        get_state_func=state_pollers.get_memory_usage
    ),
    base_classes.create_sensor(
        name="Disk_Usage_Root",
        unit_of_measurement="%",
        device_class="power_factor",
        icon="mdi:harddisk",
        get_state_func=state_pollers.get_disk_usage
    ),
    base_classes.create_sensor(
        name="Core_Voltage",
        unit_of_measurement="V",
        device_class=None,
        icon="mdi:flash",
        get_state_func=state_pollers.get_core_voltage
    ),
    base_classes.create_sensor(
        name="CPU_Frequency",
        unit_of_measurement="MHz",
        device_class=None,
        icon="mdi:speedometer",
        get_state_func=state_pollers.get_cpu_frequency
    ),
    base_classes.create_sensor(
        name="GPU_Frequency",
        unit_of_measurement="MHz",
        device_class=None,
        icon="mdi:chip",
        get_state_func=state_pollers.get_gpu_frequency
    ),
]


